version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-29-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew   