version: 2
sudo:  required
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-29-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew   
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Debug
          command: |
           - chmod +x ./gradlew
           - ./gradlew clean assembleDebug
      - store_artifacts: 
          path: /app/build/outputs/apk/debug/*.apk
          destination: /apk-debug   
      - run:
          name: Build Release
          command: |
           - chmod +x ./gradlew
           - ./gradlew clean assembleRelease
      - store_artifacts: 
          path: /app/build/outputs/apk/release/*.apk
          destination: /apk-release 
     deploy:
      steps:
       - checkout
       - aws-s3/sync:
           from: /apk-release
           to: 's3://my-s3-bucket-name/prefix'
           arguments: | # Optional arguments
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true # default is false
                  